# This triggers testing on major libs so we can verify we did not break anything
# These repos MUST HAVE:
# - tests.yml workflow that is triggered by workflow_dispatch
# - development branch
# - A test for boxlang@be
name: Trigger Box Tests

on:
  # Trigger on the completion of the Snapshots workflow
  workflow_run:
    workflows: [Snapshots]
    types: [completed]
    branches:
      - "development"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        repo:
          - "coldbox/coldbox-platform"
          - "ortus-solutions/testbox"

    steps:
      - name: Trigger Test Workflow for ${{ matrix.repo }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_BOXES }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/tests.yml/dispatches \
            -d '{"ref": "development"}'
